### ISSUE TITLE
Example: openrewrite with Batch Changes

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/batch-change-examples#14]
Currently, we don't have a good  Java example. [openrewrite](https://github.com/openrewrite/rewrite) is a good candidate to showcase.

The [current example](https://github.com/sourcegraph/batch-change-examples/commit/daa7001280d63fe1396dddf0b9369d1f82021f3f) (WIP) highlights a few friction points, that could be solved by showing a better tutorial.
openrewrite is AST-based, and it runs alongside build tool (eg. gradle). Running openrewrite requires making changes to the build config (config `build.gradle`) to add the rewrite plugin, and list recipes. This means that automating a code change requires:
- automating (tempoary) changes to the build config reliably
- in case [recipes](https://docs.openrewrite.org/reference/yaml-format-reference) outside the default ones are added, copying them over to the container used in a batch change
- discriminating between versions of Jaca and the build system before making a change

**Comment by mrnugget** [comment]
@malomarrec curious why it's re-opened and in progress? I thought https://github.com/sourcegraph/batch-change-examples/pull/27 fixed it?

**Comment by malomarrec** [comment]
Ah. I think automation did that.
